#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# alias t='tmux attach -d $1'
t () {
	if ([[ $# -eq 0 ]])
	then
		tmux attach -d;
	else
		tmux attach -d -t $1
	fi
}
